name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }} • ${{ matrix.compiler || 'default' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
            cc: gcc
            cxx: g++
          - os: ubuntu-latest
            compiler: clang
            cc: clang
            cxx: clang++
          - os: macos-latest
            compiler: appleclang
            cc: clang
            cxx: clang++
          - os: windows-latest
            compiler: msvc

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Prepare MSVC environment for command-line builds
      - name: MSVC Dev Cmd
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Test
        run: ctest --test-dir build --output-on-failure --build-config Release
